"""empty message

Revision ID: 515ee6cd896d
Revises: 
Create Date: 2019-03-11 16:50:30.917311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515ee6cd896d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channelId', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('playlistId', sa.String(length=100), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('confirm', sa.Integer(), nullable=True),
    sa.Column('channel_type', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.Column('searched', sa.Boolean(), nullable=True),
    sa.Column('monetization', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channelId')
    )
    op.create_table('website',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rss_url', sa.String(length=100), nullable=True),
    sa.Column('political_leaning', sa.String(length=100), nullable=True),
    sa.Column('alexa_ranking', sa.Integer(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('domain_registered', sa.String(length=100), nullable=True),
    sa.Column('domain_updated', sa.String(length=100), nullable=True),
    sa.Column('generator', sa.String(length=120), nullable=True),
    sa.Column('full_rss', sa.Text(), nullable=True),
    sa.Column('dead', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('website_Id', sa.Integer(), nullable=True),
    sa.Column('last_search', sa.DateTime(), nullable=True),
    sa.Column('searched', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['website_Id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('videoId', sa.String(length=100), nullable=False),
    sa.Column('channel_Id', sa.Integer(), nullable=True),
    sa.Column('website_Id', sa.Integer(), nullable=True),
    sa.Column('article_Id', sa.Integer(), nullable=True),
    sa.Column('needs_stats', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('manual', sa.Boolean(), nullable=True),
    sa.Column('searched', sa.Boolean(), nullable=True),
    sa.Column('monetization', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['article_Id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['channel_Id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['website_Id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('videoId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('article')
    op.drop_table('website')
    op.drop_table('channel')
    # ### end Alembic commands ###
